### ISSUE TITLE
how to run this code

### ISSUE THREAD

**Issue by dpbnnp** [chiachong/medium-search-app#1]
could you tell me how to run this code and the architecture of this project?

**Comment by chiachong** [comment]
Hey, you may follow my medium [post](https://medium.com/better-programming/build-a-search-engine-for-medium-stories-using-streamlit-and-elasticsearch-b6e717819448) for the details of this project, you may open a new issue if you have problem following the post. Thanks.

**Comment by dpbnnp** [comment]
thanks
